Order of kinetic energy computation
CliMA/ClimaAtmos.jl pull request #1242
Opened 2023-01-17 18:34 UTC by akshaysridhar

### Purpose
Splits the third change from #1234 : order of interpolation in kinetic energy changes.

2023-01-17 18:55 UTC, akshaysridhar commented
Changes affect MSE tables : Could someone please confirm this is acceptable ?

2023-01-17 18:59 UTC, szy21 commented
My understanding is that we don't need to merge this now? @Zhengyu-Huang ?

2023-01-17 19:55 UTC, akshaysridhar commented
> My understanding is that we don't need to merge this now? @Zhengyu-Huang ?

That's my understanding as well - #1240 is the first in the sequence of PRs we need to merge (the weighted interpolation component changes are separated in that one)

2023-01-25 11:57 UTC, tapios commented
Could we isolate the KE computation to a function, so we do not have to repeat this code so many times and can apply the changes necessary once?

2023-01-25 18:23 UTC, simonbyrne commented
@akshaysridhar rather than try to merge the commit, use `git cherry-pick` to pull out the single commit from #1234

2023-01-25 19:28 UTC, simonbyrne requested changes

2023-01-25 19:28 UTC, simonbyrne commented on docs/Manifest.toml
> +=======
Cherry picking the commit will avoid this problem

2023-01-25 20:15 UTC, tapios commented
> Could we isolate the KE computation to a function, so we do not have to repeat this code so many times and can apply the changes necessary once?

We need two things here (or in whatever becomes of this):
1.  Isolate the KE changes to one place (rather than repeating the same changes many times)
2. Document how KE is being computed. (It looks like there is some assumption of orthogonality between horizontal and vertical components, which wouldn't be true in generalized coordinates. I would like to be able to understand what is happening here.)

2023-02-15 22:11 UTC, akshaysridhar commented
@simonbyrne Here are the changes related to the `compute_kinetic!` utility; buildkite checks are passing so I'm ready to merge this with your approval.

2023-02-15 22:44 UTC, akshaysridhar commented
bors r-

2023-02-15 23:00 UTC, akshaysridhar commented
bors r+

2023-02-15 23:47 UTC, merged