Define set on for fields
CliMA/ClimaAtmos.jl pull request #239
Opened 2022-02-25 23:53 UTC by charleskawczynski

I'd like to propose adding `set!` for ClimaCore fields, and using this instead, as it alleviates assumptions about the model structure. This is a tracer bullet PR demo-ing the idea.

2022-02-26 01:50 UTC, bischtob commented
I like this

2022-02-26 01:52 UTC, bischtob approved these changes
This is a nice change. We may be able to modularize the big functions here even further in the future.

2022-02-26 01:52 UTC, bischtob commented
bors try

2022-02-26 04:57 UTC, jiahe23 commented on test/test_cases/run_1d_ekman_column.jl
> +        set!(model.thermodynamics.ρθ, ρθ)
This change should propagates to other cases under `test/test_cases/`

2022-02-26 04:59 UTC, jiahe23 requested changes
changes needed for all cases under the test_cases folder

2022-02-26 05:06 UTC, jiahe23 commented on test/test_cases/run_1d_ekman_column.jl
> +        set!(model.w, w)
```suggestion
        set!(model.base.ρ, ρ)
        set!(model.base.uv, uv)
        set!(model.base.w, w)
```

2022-02-28 18:15 UTC, charleskawczynski commented
bors try

2022-02-28 18:32 UTC, charleskawczynski commented on test/test_cases/run_1d_ekman_column.jl
> +        set!(model.base.ρ, ρ)
@bischtob, do you know what this should be?

2022-02-28 18:34 UTC, charleskawczynski commented on test/test_cases/run_1d_ekman_column.jl
> +        set!(model.base.ρ, ρ)
Oh, maybe we need `set!(simulation.integrator.ρ)` or `set!(simulation.integrator.base.ρ)` etc.

2022-02-28 18:36 UTC, charleskawczynski commented on test/test_cases/run_1d_ekman_column.jl
> +        set!(model.base.ρ, ρ)
Yeah, that makes more sense.

2022-02-28 18:53 UTC, charleskawczynski commented
bors try

2022-03-23 18:50 UTC, jiahe23 approved these changes
LGTM

2022-03-23 21:52 UTC, jiahe23 commented
bors try

2022-03-23 23:19 UTC, jiahe23 commented on test/test_cases/run_1d_ekman_column.jl
> +        set!(Y.base.ρ, ρ)
Oh I see the problem... Here `@unpack ρ, uv, w, ρθ = init_1d_ekman_column(FT, params)` gives `ρ, uv, w, ρθ` as functions not the fields.

2022-03-23 23:20 UTC, jiahe23 commented on src/Simulations/simulation.jl
> -            target_field .= f
Here it gives the flexibility to initialize from either a know function (of locations) or a known fields

2022-04-01 16:48 UTC, bischtob commented
@charleskawczynski is this ready?

2022-04-04 17:06 UTC, charleskawczynski commented
@bischtob, this doesn't seem to work, any idea why?

2022-04-11 19:41 UTC, closed without merging