Enable distributed 3D simulation option
CliMA/ClimaAtmos.jl pull request #267
Opened 2022-04-01 16:56 UTC by akshaysridhar

Modify function spaces to enable box-3D distributed simulations
WIP
	modified:   make_function_space.jl

2022-04-01 22:02 UTC, akshaysridhar commented
Awaiting changes from ClimaCore #631 before merging this (it should simplify ClimaAtmos changes a fair bit)

2022-04-05 20:32 UTC, bischtob requested changes
Nice. Just a few tiny things.

2022-04-05 20:32 UTC, bischtob commented on src/Simulations/simulation.jl
> +    space_center, space_face, comms_ctx_center, comms_ctx_face =
`comms_ctx_xyz` could be `comms_context_xyz`

2022-04-05 20:32 UTC, bischtob commented on test/test_domains.jl
>          @test domain.stretching isa Uniform
add a todo for the upcoming tests

2022-04-05 21:09 UTC, sriharshakandala commented on src/Models/Nonhydrostatic3DModels/equations_base_model.jl
> +    Spaces.weighted_dss!(dρ, comms_ctx_center)
We are currently using a conservatively sized comms_ctx for both face and center DSS in ClimaCore

2022-04-20 20:14 UTC, akshaysridhar commented
631 in ClimaCore is in, I'll udpate this PR  and request a second review.

2022-09-02 22:13 UTC, closed without merging