first commit
CliMA/ClimaAtmos.jl pull request #81
Opened 2021-09-03 23:02 UTC by szy21

Closes #77

2021-09-04 23:59 UTC, bischtob commented on README.md
> +$ cd ClimateMachine.jl
:) maybe not?

2021-09-04 23:59 UTC, bischtob requested changes
Just a few typos to correct. Otherwise this is good!

2021-09-05 00:00 UTC, bischtob commented
Please also squash your commits and rebase on master so that we can merge it after the corrections :).

2021-09-05 01:02 UTC, szy21 commented on README.md
> +$ cd ClimateMachine.jl
🤦‍♀️

2021-09-05 01:14 UTC, szy21 commented
@bischtob I just fixed the typos and rebased it. Thanks!

2021-09-05 01:32 UTC, bischtob commented
Thank you @szy21. Great work.

2021-09-05 01:33 UTC, bischtob approved these changes
LGTM

2021-09-05 01:33 UTC, bischtob commented
bors r+

2021-09-05 01:43 UTC, merged